sudo: required
dist: trusty

language: cpp
osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:george-edison55/cmake-3.x -y;
      sudo apt-get update -q;
      sudo apt-get upgrade cmake -y;
      sudo apt-get install python3 -y;
      sudo apt-get upgrade libboost-all-dev -y;
      git clone https://github.com/samtools/htslib.git;
      cd htslib && autoheader && autoconf && ./configure && make && sudo make install;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew outdated cmake || upgrade cmake;
      brew install python3;
      brew outdated boost || upgrade boost;
      brew tap homebrew/science;
      brew install htslib;
    fi

matrix:
#  include:
#  - os: linux
#    compiler: gcc
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#      packages:
#        - g++-6
#    env: COMPILER=g++-6
  - os: osx
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
        packages:
          - clang-3.8
    install: export PATH=/usr/local/clang/bin/clang:$PATH
    env: COMPILER=clang++-3.8

script:
  - ./install.py --compiler=$COMPILER