sudo: required
dist: trusty

language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
      packages:
        - g++-6
    env: COMPILER=g++-6
  - os: osx
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
        packages:
          - clang-3.8
    env: COMPILER=clang++-3.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:george-edison55/cmake-3.x;
      sudo apt-get update;
      sudo apt-get -q -y upgrade cmake;
      sudo apt-get -q -y install python3;
      sudo apt-get -q -y upgrade libboost-all-dev;
      git clone https://github.com/samtools/htslib.git;
      cd htslib;
      autoheader;
      autoconf;
      ./configure;
      make && make install;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew upgrade cmake;
      brew install python3;
      brew upgrade boost;
      brew tap homebrew/science;
      brew install htslib;
      export CXX="clang++-3.8" CC="clang-3.8"
    fi

script:
  - echo ${PATH}
  - ${CXX} --version
  - ${CXX} -v
  - ./install.py --compiler=$COMPILER